### PR TITLE
Fixes two-point flux approximation in MPFA-O

### LINKED ISSUE #130: Debug mismatch between MPFA-O TPF and PFLOTRAN
MPFA-O can be reduced to two-point flux approximation via:
```
-tdy_mpfao_gmatrix_method          MPFAO_GMATRIX_TPF \
-tdy_mpfao_boundary_condition_type MPFAO_DIRICHLET_BC
```

Debug why MPFA-O TPF does not match PFLTORAN.

### PR DESCRIPTION
**Pull request by bishtgautam**
- The exponential density function is corrected to ensure that density is constant if the pressure
   is below the reference pressure. This change required gold files to be updated for tests using
   exponential density function.
- The face permeability for internal faces in the TPF is modified to be consistent with PFLOTRAN's
   approach of first converting cell centered tensor permeability to a scalar and then harmonically
   averaging the two scalar permeabilities. This change required update of gold files for TPF tests.
- The contribution of the gravity term is accounted as a two-point flux (similar to PFLOTRAN's
  implementation) based on  [Starnoni et al. (2019)](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2019WR025384?af=R&ai=1gvoi&mi=3ricys
)

Fixes #130

### CODE REVIEW

**Comment by bishtgautam** [comment]
It seems that the branch was initially not deployed because it had a conflict. I have now rebased the branch.

**Comment by jeff-cohere** [comment]
Is the test failure expected (gold file needs updating, perhaps)?

File: include/private/tdymeshimpl.h [hunk 1]
```diff
@@ -52,6 +52,7 @@ typedef struct {
   PetscInt *is_face_up;                            /* true if the face->cell_ids[0] is upwind of face->cell_ids[1] in cell traversal order*/
   PetscInt *face_unknown_idx;                      /* index of the unknown associated with the face within the vector interface unknowns common to a vertex*/
   PetscInt *face_flux_idx;                         /* index of the fluxes (internal, up, and down) associated with the face */
+  PetscInt *vertex_ids;
```
Comment (jeff-cohere) [inline include/private/tdymeshimpl.h:55]: Ah, yes. I was wondering why this was missing.

File: src/mesh/tdycoremeshutils.c [hunk 2]
```diff
@@ -888,6 +888,48 @@ PetscErrorCode TDyGetCellNaturalIDsLocal(TDy tdy, PetscInt *ni, PetscInt nat_ids
...
+/// Finds the id of subcell in the mesh->subcells struct that corresponds to
+/// cell_id and vertex_id and face_id.
+/// 
+/// @param [in] tdy A TDy struct
+/// @param [in] cell_id ID of cell
+/// @param [in] vertix_id ID of vertex
+/// @param [in] face_id ID of face
+/// @param [out] *subcell_id ID of subcell
+/// @returns 0 on success, or a non-zero error code on failure
+PetscErrorCode TDyGetSubcellIDGivenCellIdVertexIdFaceId(TDy tdy, PetscInt cell_id, PetscInt vertex_id, PetscInt face_id, PetscInt *subcell_id){
```
Comment (jeff-cohere) [inline src/mesh/tdycoremeshutils.c:901]: I'll see if I can't work this into the refactored mesh interface.

File: src/mpfao/3D/tdympfao3D_core.c [hunk 3]
```diff
@@ -110,9 +111,61 @@ PetscErrorCode TDyComputeGMatrixFor3DMesh(TDy tdy) {
 
           case MPFAO_GMATRIX_TPF:
             if (ii == jj) {
+              /*
```
Comment (jeff-cohere) [inline src/mpfao/3D/tdympfao3D_core.c:114]: Do we want to keep this code commented out, or just get rid of it?

File: src/mpfao/3D/tdympfao3D_core.c [hunk 4]
```diff
@@ -979,3 +1032,317 @@ PetscErrorCode TDyComputeTransmissibilityMatrix3DMesh(TDy tdy) {
   PetscFunctionReturn(0);
 
 }
+
+/* -------------------------------------------------------------------------- */
+/// Computes unit vector joining upwind and downwind cells that share a face.
```
Comment (jeff-cohere) [inline src/mpfao/3D/tdympfao3D_core.c:1037]: Maybe we should mention that this unit vector points from the centroid of the upwind cell to that of the downwind cell.

File: src/mpfao/3D/tdympfao3D_core.c [hunk 5]
```diff
@@ -979,3 +1032,317 @@ PetscErrorCode TDyComputeTransmissibilityMatrix3DMesh(TDy tdy) {
...
+///
+/// @param [in] tdy A TDy struct
+/// @param [in] face_id ID of the face
+/// @param [out] *up2dn_uvec[3] Unit vector from upwind to downwind cell
```
Comment (jeff-cohere) [inline src/mpfao/3D/tdympfao3D_core.c:1041]: Let's just use up2dn_uvec for the parameter name.

File: src/mpfao/3D/tdympfao3D_core.c [hunk 6]
```diff
@@ -979,3 +1032,317 @@ PetscErrorCode TDyComputeTransmissibilityMatrix3DMesh(TDy tdy) {
...
+  PetscFunctionReturn(0);
+}
+
+/* -------------------------------------------------------------------------- */
+/// Computes upwind and downwind distance of cells sharing a face. If the face is a
+/// boundary face, one of the distance is zero
+///
+/// @param [in] tdy A TDy struct
+/// @param [in] face_id ID of the face
+/// @param [out] *dist_up Distance between the upwind cell centroid and face centroid
```
Comment (jeff-cohere) [inline src/mpfao/3D/tdympfao3D_core.c:1089]: We can leave the asterisk out of these parameter names.

File: src/mpfao/3D/tdympfao3D_core.c [hunk 7]
```diff
@@ -979,3 +1032,317 @@ PetscErrorCode TDyComputeTransmissibilityMatrix3DMesh(TDy tdy) {
...
+  PetscFunctionReturn(0);
+}
+
+/* -------------------------------------------------------------------------- */
+/// Computes face permeability tensor as a harmonically distance-weighted
+//  permeability of upwind and downwind permeability tensors
+///
+/// @param [in] tdy A TDy struct
+/// @param [in] face_id ID of the face
+/// @param [out] Kup[9] upwind permeability tensor
```
Comment (jeff-cohere) [inline src/mpfao/3D/tdympfao3D_core.c:1139]: Let's remove [9] and describe this and the following line as "components of the upwind/downwind permeability tensor"

Comment (jeff-cohere) [reply src/mpfao/3D/tdympfao3D_core.c:1139]: and maybe indicate whether the components are stored in row-major or column-major order.

File: src/mpfao/3D/tdympfao3D_core.c [hunk 8]
```diff
@@ -979,3 +1032,317 @@ PetscErrorCode TDyComputeTransmissibilityMatrix3DMesh(TDy tdy) {
...
+
+/* -------------------------------------------------------------------------- */
+/// Computes face permeability tensor as a harmonically distance-weighted
+//  permeability of upwind and downwind permeability tensors
+///
+/// K = (wt_1 * K_u^{-1} + (1-wt_1) * K_d^{-1})^{-1}
+///
+/// @param [in] tdy A TDy struct
+/// @param [in] face_id ID of the face
+/// @param [out] Kface[9] face permeability tensor
```
Comment (jeff-cohere) [inline src/mpfao/3D/tdympfao3D_core.c:1180]: See above remarks for how to describe this.

File: src/mpfao/3D/tdympfao3D_core.c [hunk 9]
```diff
@@ -979,3 +1032,317 @@ PetscErrorCode TDyComputeTransmissibilityMatrix3DMesh(TDy tdy) {
...
+///   GravDis = gravity discretization term that is not dependent on the unknown variable(s)
+///             such as pressure, temperautre. Thus, this term is precomputed.
+/// 
+/// Starnoni, M., Berre, I., Keilegavlen, E., & Nordbotten, J. M. (2019).
+/// Consistent mpfa discretization for flow in the presence of gravity. Water
+/// Resources Research, 55, 10105– 10118. https://doi.org/10.1029/2019WR025384
+/// 
+/// @param [in] tdy A TDy struct
+/// @returns 0 on success, or a non-zero error code on failure
+PetscErrorCode TDyComputeGravityDiscretizationFor3DMesh(TDy tdy) {
```
Comment (jeff-cohere) [inline src/mpfao/3D/tdympfao3D_core.c:1252]: We could call this something like `TDyComputeTPFGravityTerm3D` to indicate that it's a TPF term.

File: src/mpfao/3D/tdympfao3D_ts.c [hunk 10]
```diff
@@ -75,8 +77,15 @@ PetscErrorCode TDyMPFAOIFunction_Vertices_3DMesh(Vec Ul, Vec R, void *ctx) {
       cell_id_up = faces->cell_ids[fOffsetCell + 0];
       cell_id_dn = faces->cell_ids[fOffsetCell + 1];
 
+      den = 0.0;
+      if (cell_id_up>=0) den += tdy->rho[cell_id_up];
```
Comment (jeff-cohere) [inline src/mpfao/3D/tdympfao3D_ts.c:81]: This style is a little loose for C. Would you mind doing something like the following?

```
if (cell_id_up>=0) {
  den += tdy->rho[cell_id_up];
} else {
  den += tdy->rho_BND[-cell_id_up-1];
}

File: src/mpfao/3D/tdympfao3D_ts.c [hunk 11]
```diff
@@ -75,8 +77,15 @@ PetscErrorCode TDyMPFAOIFunction_Vertices_3DMesh(Vec Ul, Vec R, void *ctx) {
...
+      else               den += tdy->rho_BND[-cell_id_up-1];
+      if (cell_id_dn>=0) den += tdy->rho[cell_id_dn];
+      else               den += tdy->rho_BND[-cell_id_dn-1];
+      den *= 0.5;
+
       // Upwind the 'ukvr'
-      if (TtimesP[irow] < 0.0) { // up ---> dn
+      if (TtimesP[irow] + den*GravDis_ptr[face_id*num_subfaces + subface_id]< 0.0) { // up ---> dn
```
Comment (jeff-cohere) [inline src/mpfao/3D/tdympfao3D_ts.c:88]: Since we make use of `GravDis_ptr[face_id*num_subfaces + subface_id]` here and below, maybe we could use something like `g` or `gravity` or something that indicates that it's the appropriate value for the gravity vector.

File: src/mpfao/tdympfao.c [hunk 12]
```diff
@@ -440,6 +467,7 @@ PetscErrorCode TDyMPFAOInitialize(TDy tdy) {
   // why must these be placed after SetPermeabilityFromFunction()?
   ierr = ComputeGMatrix(tdy); CHKERRQ(ierr);
```
Comment (jeff-cohere) [inline src/mpfao/tdympfao.c:468]: At some point, it might make sense for us to break state data out of the model itself. It's very strange to just call a bunch of methods on an object and hope that it's in the right state before/afterward.

File: src/mpfao/3D/tdympfao3D_ts.c [hunk 13]
```diff
@@ -373,6 +389,200 @@ PetscErrorCode TDyMPFAOIJacobian_Vertices_3DMesh(Vec Ul, Mat A, void *ctx) {
   PetscFunctionReturn(0);
 }
 
+/* -------------------------------------------------------------------------- */
+/// Computes the jacobian for the Richards equation for two-point flux
+///
+/// @param [in] Ul current value of the iterate
+/// @param [out] A matrix for the jacobian
+/// @param [in] *ctx user-defined context
```
Comment (jeff-cohere) [inline src/mpfao/3D/tdympfao3D_ts.c:397]: No asterisk

File: src/mpfao/3D/tdympfao3D_ts.c [hunk 14]
```diff
@@ -373,6 +389,200 @@ PetscErrorCode TDyMPFAOIJacobian_Vertices_3DMesh(Vec Ul, Mat A, void *ctx) {
...
+      if (cell_id_dn>=0) den += tdy->rho[cell_id_dn];
+      else               den += tdy->rho_BND[-cell_id_dn-1];
+      den *= 0.5;
+
+      PetscInt num_subfaces = 4;
+      if (TtimesP[irow] + den*GravDis_ptr[face_id*num_subfaces + subface_id]< 0.0) { // up ---> dn
+        // Flow: up --> dn
+        if (cell_id_up>=0) {
+          // "up" is an internal cell
+          ukvr       = cc->Kr[cell_id_up]/tdy->vis[cell_id_up];
```
Comment (jeff-cohere) [inline src/mpfao/3D/tdympfao3D_ts.c:490]: This could be cleaned up with some temporary variables. A lot of these are pulled from arrays repeatedly. The compiler knows how to optimize this kind of stuff, but symbolic names might help the humans.

File: src/mpfao/3D/tdympfao3D_ts.c [hunk 15]
```diff
@@ -373,6 +389,200 @@ PetscErrorCode TDyMPFAOIJacobian_Vertices_3DMesh(Vec Ul, Mat A, void *ctx) {
...
+                       cc->Kr[cell_id_dn]/(tdy->vis[cell_id_dn]*tdy->vis[cell_id_dn])*tdy->dvis_dP[cell_id_dn];
+        } else {
+          // "dn" is a boundary cell
+          ukvr       = cc_bnd->Kr[-cell_id_dn-1]/tdy->vis_BND[-cell_id_dn-1];
+          dukvr_dPdn = 0.0;//cc_bnd->dKr[-cell_id_dn-1]*cc_bnd->dS_dP[-cell_id_dn-1]/tdy->vis_BND[-cell_id_dn-1];
+        }
+      }
+
+      // If one of the cell is on the boundary
+      if (cell_id_up<0) cell_id_up = cell_id_dn;
```
Comment (jeff-cohere) [inline src/mpfao/3D/tdympfao3D_ts.c:514]: If you don't mind, let's use curly braces for `if` tests, even if they're one-liners. This makes it easier for people to add logic.

File: src/mpfao/3D/tdympfao3D_core.c [hunk 16]
```diff
@@ -979,3 +1032,317 @@ PetscErrorCode TDyComputeTransmissibilityMatrix3DMesh(TDy tdy) {
...
+      PetscInt fOffsetCell = faces->cell_offset[face_id];
+      PetscInt cell_id_up = faces->cell_ids[fOffsetCell + 0];
+      PetscInt cell_id_dn = faces->cell_ids[fOffsetCell + 1];
+
+      // Currently, only zero-flux neumann boundary condition is implemented.
+      // If the boundary condition is neumann, then gravity discretization term is zero
+      if (tdy->mpfao_bc_type == MPFAO_NEUMANN_BC && (cell_id_up < 0 || cell_id_dn < 0)) continue;
+
+      PetscInt cell_id;
+      if (cell_id_up < 0) cell_id = cell_id_dn;
```
Comment (jeff-cohere) [inline src/mpfao/3D/tdympfao3D_core.c:1298]: See comments elsewhere for my thoughts on one-liner `if` tests.

**Review by jeff-cohere — CHANGES_REQUESTED** [review]
Looks pretty good! I left some comments about some very minor changes. Also, we should probably get that last regression test working.

File: src/mpfao/3D/tdympfao3D_core.c (hunk 9 above)
Comment (bishtgautam) [reply src/mpfao/3D/tdympfao3D_core.c:1248]: In a future PR, this function will be used by the non-TPF code.

**Comment by bishtgautam** [comment]
@jeff-cohere The PR is now ready for a second review.

**Comment by bishtgautam** [comment]
I broke a test and am working on fixing it.

**Comment by bishtgautam** [comment]
I now broke a bunch of other tests :(

**Comment by jeff-cohere** [comment]
> I now broke a bunch of other tests :(

No sweat! Let me know if you need any extra eyes on anything, and otherwise I'll just re-review when tests are fixed.

**Comment by bishtgautam** [comment]
Tests are now fixed.

**Review by jeff-cohere — APPROVED** [review]
