### PR TITLE
Fixes namespace

### LINKED ISSUE #113: Use internal (or static) linkage for anything that should not be in the public API
Based on @jedbrown's [comment in #105](https://github.com/TDycores-Project/TDycore/issues/105#issuecomment-710475904).

### PR DESCRIPTION
**Pull request by bishtgautam**
Multiple internal functions are changed from `PETSC_EXTERN` to `PETSC_INTERN`

Fixes #113

### CODE REVIEW

File: demo/richards/richards_driver.c [hunk 1]
```diff
@@ -37,8 +35,10 @@ int main(int argc, char **argv) {
   ierr = TDySetFromOptions(tdy); CHKERRQ(ierr);
 
   ierr = TDyDriverInitializeTDy(tdy); CHKERRQ(ierr);
-  if (!rank) tdy->io->io_process = PETSC_TRUE;
-  tdy->io->print_intermediate = print_intermediate;
+  if (!rank) {
```
Comment (jeff-cohere) [inline demo/richards/richards_driver.c:38]: Not a big deal, but if you are using `!rank` here to mean `rank 0`, then `if (rank == 0)` is more clear.

File: include/private/tdympfaoimpl.h [hunk 2]
```diff
@@ -4,7 +4,6 @@
 #include <petsc.h>
 
 PETSC_EXTERN PetscErrorCode TDyMPFAOInitialize(TDy);
```
Comment (jeff-cohere) [inline include/private/tdympfaoimpl.h:6]: Just to check: do you want external linkage on this function? Does one of the drivers use it?

File: include/tdycore.h [hunk 3]
```diff
@@ -77,19 +77,18 @@ PETSC_EXTERN PetscErrorCode TDyInit(int argc, char* argv[]);
...
 PETSC_EXTERN PetscErrorCode TDyFinalize(void);
 
-PETSC_EXTERN PetscErrorCode TDyCreate(TDy *tdy);
-PETSC_EXTERN PetscErrorCode TDySetMode(TDy tdy, TDyMode mode);
-PETSC_EXTERN PetscErrorCode TDySetDiscretizationMethod(TDy tdy,
-                                                       TDyMethod method);
-PETSC_EXTERN PetscErrorCode TDySetDM(TDy tdy,DM dm);
-PETSC_EXTERN PetscErrorCode TDySetFromOptions(TDy tdy);
-PETSC_EXTERN PetscErrorCode TDySetupNumericalMethods(TDy tdy);
+PETSC_EXTERN PetscErrorCode TDyCreate(TDy*);
```
Comment (jeff-cohere) [inline include/tdycore.h:80]: I'm not sure we want to get rid of these parameter names for functions that belong to TDycore's public API. If we adopt a Doxygen-style approach to annotating source code, we would describe these parameter names in the annotations. Of course, we can annotate the implementations instead of the declarations, but many folks are used to browsing header files to see what a library can do.

**Review by jeff-cohere — APPROVED** [review]
Looks good. I left some comments that we can discuss. The only thing I might change is the omission of all the parameter names from function declarations in headers, because they're arguably a part of our reference documentation approach.

File: demo/richards/richards_driver.c (hunk 1 above)
Comment (jedbrown) [reply demo/richards/richards_driver.c:38]: I don't disagree, but this is a PETSc convention that Barry felt very strongly about so we (PETSc developers) always write `!rank`.

File: include/private/tdympfaoimpl.h (hunk 2 above)
Comment (bishtgautam) [reply include/private/tdympfaoimpl.h]: Good catch. I have fixed this now.

File: demo/richards/richards_driver.c (hunk 1 above)
Comment (bishtgautam) [reply demo/richards/richards_driver.c:38]: I simply followed the existing code and don't have a strong opinion either way. One more reason to have a style guide.

File: include/tdycore.h (hunk 3 above)
Comment (bishtgautam) [reply include/tdycore.h:80]: I'm here following PETSc's developer manual. Another reason for us to have our own style guide.

Comment (jeff-cohere) [reply include/tdycore.h:80]: Sounds like we need a style guide!

Comment (jedbrown) [reply include/tdycore.h:80]: The rationale for the PETSc style guide is that the compiler doesn't check the names appearing here so they can become outdated and thus misleading.

Comment (jeff-cohere) [reply include/tdycore.h:80]: That makes sense for an approach that doesn't annotate header files. If we decide to annotate our functions in their implementations instead of headers, then this approach is fine.
